kind: project
metadata:
  name: mlopspedia-admin
  created: '2023-05-09T16:31:52.073000'
spec:
  functions:
  - url: src/data_collection.py
    name: data-collecting
    kind: job
  - url: src/data_preprocess.py
    name: data-preparing
    kind: job
  - url: src/trainer.py
    name: mpi-training
    kind: mpijob
    image: yonishelach/mlrun-hf-gpu
  - url: src/trainer.py
    name: training
    kind: job
  - url: src/serving.py
    name: serving-gpt2
    kind: serving
  - url: src/serving.py
    name: serving-mlopspedia
    kind: serving
  - url: src/testing.py
    name: testing
    kind: job
    handler: model_server_tester
  - name: serving-gpt2-gpu
    spec:
      kind: serving
      metadata:
        name: serving-gpt2-gpu
        project: mlopspedia-admin
      spec:
        command: ''
        args: []
        image: yonishelach/mlrun-hf-gpu
        build:
          functionSourceCode: aW1wb3J0IG9zCmltcG9ydCB6aXBmaWxlCmZyb20gdHlwaW5nIGltcG9ydCBBbnksIERpY3QsIFVuaW9uCmltcG9ydCBudW1weSBhcyBucAppbXBvcnQgdHJhbnNmb3JtZXJzCgppbXBvcnQgbWxydW4uYXJ0aWZhY3RzCmZyb20gbWxydW4uc2VydmluZy52Ml9zZXJ2aW5nIGltcG9ydCBWMk1vZGVsU2VydmVyCgppbXBvcnQgdG9yY2gKaW1wb3J0IGV2YWx1YXRlCgpTVUJKRUNUX01BUksgPSAiU3ViamVjdDogIgpDT05URU5UX01BUksgPSAiXG5Db250ZW50OiAiClBST01QVF9GT1JNQVQgPSBTVUJKRUNUX01BUksgKyAie30iICsgQ09OVEVOVF9NQVJLCgoKZGVmIGNsZWFuX3ByZXByb2Nlc3ModGV4dDogVW5pb25bc3RyLCBieXRlc10pIC0+IGRpY3Q6CiAgICBpZiBpc2luc3RhbmNlKHRleHQsIGJ5dGVzKToKICAgICAgICB0ZXh0ID0gdGV4dC5kZWNvZGUoInV0Zi04IikKICAgIHJldHVybiB7ImlucHV0cyI6IFtzdHIodGV4dCldfQoKCmRlZiBwcmVwcm9jZXNzKHRleHQ6IFVuaW9uW3N0ciwgYnl0ZXNdKSAtPiBkaWN0OgogICAgIyBGb3JtYXQgdGhlIHByb21wdCBhcyBzdWJqZWN0OgogICAgaWYgaXNpbnN0YW5jZSh0ZXh0LCBieXRlcyk6CiAgICAgICAgdGV4dCA9IHRleHQuZGVjb2RlKCJ1dGYtOCIpCiAgICByZXR1cm4geyJpbnB1dHMiOiBbUFJPTVBUX0ZPUk1BVC5mb3JtYXQoc3RyKHRleHQpKV19CgoKY2xhc3MgTExNTW9kZWxTZXJ2ZXIoVjJNb2RlbFNlcnZlcik6CiAgICBkZWYgX19pbml0X18oCiAgICAgICAgc2VsZiwKICAgICAgICBjb250ZXh0OiBtbHJ1bi5NTENsaWVudEN0eCA9IE5vbmUsCiAgICAgICAgbmFtZTogc3RyID0gTm9uZSwKICAgICAgICBtb2RlbF9jbGFzczogc3RyID0gTm9uZSwKICAgICAgICB0b2tlbml6ZXJfY2xhc3M6IHN0ciA9IE5vbmUsCiAgICAgICAgIyBMb2FkIGZyb20gTUxSdW4gYXJnczoKICAgICAgICBtb2RlbF9wYXRoOiBzdHIgPSBOb25lLAogICAgICAgICMgTG9hZCBmcm9tIGh1YiBhcmdzOgogICAgICAgIG1vZGVsX25hbWU6IHN0ciA9IE5vbmUsCiAgICAgICAgdG9rZW5pemVyX25hbWU6IHN0ciA9IE5vbmUsCiAgICAgICAgIyBEZWVwc3BlZWQgYXJnczoKICAgICAgICB1c2VfZGVlcHNwZWVkOiBib29sID0gRmFsc2UsCiAgICAgICAgbl9ncHVzOiBpbnQgPSAxLAogICAgICAgIGlzX2ZwMTY6IGJvb2wgPSBUcnVlLAogICAgICAgICMgSW5mZXJlbmNlIGFyZ3M6CiAgICAgICAgcmVzcG9uc2VfbWF4X2xlbmd0aDogaW50ID0gMjAwLAogICAgICAgICoqY2xhc3NfYXJncywKICAgICk6CiAgICAgICAgIyBJbml0aWFsaXplIHRoZSBiYXNlIHNlcnZlcjoKICAgICAgICBzdXBlcihMTE1Nb2RlbFNlcnZlciwgc2VsZikuX19pbml0X18oCiAgICAgICAgICAgIGNvbnRleHQ9Y29udGV4dCwKICAgICAgICAgICAgbmFtZT1uYW1lLAogICAgICAgICAgICBtb2RlbF9wYXRoPW1vZGVsX3BhdGgsCiAgICAgICAgICAgICoqY2xhc3NfYXJncywKICAgICAgICApCgogICAgICAgICMgU2F2ZSBjbGFzcyBuYW1lczoKICAgICAgICBzZWxmLm1vZGVsX2NsYXNzID0gbW9kZWxfY2xhc3MKICAgICAgICBzZWxmLnRva2VuaXplcl9jbGFzcyA9IHRva2VuaXplcl9jbGFzcwoKICAgICAgICAjIFNhdmUgaHViIGxvYWRpbmcgcGFyYW1ldGVyczoKICAgICAgICBzZWxmLm1vZGVsX25hbWUgPSBtb2RlbF9uYW1lCiAgICAgICAgc2VsZi50b2tlbml6ZXJfbmFtZSA9IHRva2VuaXplcl9uYW1lCgogICAgICAgICMgU2F2ZSBkZWVwc3BlZWQgcGFyYW1ldGVyczoKICAgICAgICBzZWxmLnVzZV9kZWVwc3BlZWQgPSB1c2VfZGVlcHNwZWVkCiAgICAgICAgc2VsZi5uX2dwdXMgPSBuX2dwdXMKICAgICAgICBzZWxmLmlzX2ZwMTYgPSBpc19mcDE2CgogICAgICAgICMgU2F2ZSBpbmZlcmVuY2UgcGFyYW1ldGVyczoKICAgICAgICBzZWxmLnJlc3BvbnNlX21heF9sZW5ndGggPSByZXNwb25zZV9tYXhfbGVuZ3RoCgogICAgICAgICMgUHJlcGFyZSB2YXJpYWJsZXMgZm9yIGZ1dHVyZSB1c2U6CiAgICAgICAgc2VsZi5tb2RlbCA9IE5vbmUKICAgICAgICBzZWxmLnRva2VuaXplciA9IE5vbmUKICAgICAgICBzZWxmLl9tb2RlbF9jbGFzcyA9IE5vbmUKICAgICAgICBzZWxmLl90b2tlbml6ZXJfY2xhc3MgPSBOb25lCgogICAgZGVmIGxvYWQoc2VsZik6CiAgICAgICAgIyBHZXQgY2xhc3NlczoKICAgICAgICBzZWxmLl9tb2RlbF9jbGFzcyA9IGdldGF0dHIodHJhbnNmb3JtZXJzLCBzZWxmLm1vZGVsX2NsYXNzKQogICAgICAgIHNlbGYuX3Rva2VuaXplcl9jbGFzcyA9IGdldGF0dHIodHJhbnNmb3JtZXJzLCBzZWxmLnRva2VuaXplcl9jbGFzcykKCiAgICAgICAgIyBMb2FkIHRoZSBtb2RlbCBhbmQgdG9raW56ZXI6CiAgICAgICAgaWYgc2VsZi5tb2RlbF9wYXRoOgogICAgICAgICAgICBzZWxmLl9sb2FkX2Zyb21fbWxydW4oKQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIHNlbGYuX2xvYWRfZnJvbV9odWIoKQoKICAgICAgICAjIFVzZSBkZWVwc3BlZWQgaWYgbmVlZGVkOgogICAgICAgIGlmIHNlbGYudXNlX2RlZXBzcGVlZDoKICAgICAgICAgICAgaW1wb3J0IGRlZXBzcGVlZAoKICAgICAgICAgICAgc2VsZi5tb2RlbCA9IGRlZXBzcGVlZC5pbml0X2luZmVyZW5jZSgKICAgICAgICAgICAgICAgIG1vZGVsPXNlbGYubW9kZWwsCiAgICAgICAgICAgICAgICBtcF9zaXplPXNlbGYubl9ncHVzLAogICAgICAgICAgICAgICAgZHR5cGU9dG9yY2guZmxvYXQxNiBpZiBzZWxmLmlzX2ZwMTYgZWxzZSB0b3JjaC5mbG9hdDMyLAogICAgICAgICAgICAgICAgcmVwbGFjZV9tZXRob2Q9ImF1dG8iLAogICAgICAgICAgICAgICAgcmVwbGFjZV93aXRoX2tlcm5lbF9pbmplY3Q9VHJ1ZSwKICAgICAgICAgICAgKQoKICAgIGRlZiBfbG9hZF9mcm9tX21scnVuKHNlbGYpOgogICAgICAgICMgR2V0IHRoZSBtb2RlbCBhcnRpZmFjdCBhbmQgZmlsZToKICAgICAgICAoCiAgICAgICAgICAgIG1vZGVsX2ZpbGUsCiAgICAgICAgICAgIG1vZGVsX2FydGlmYWN0LAogICAgICAgICAgICBleHRyYV9kYXRhLAogICAgICAgICkgPSBtbHJ1bi5hcnRpZmFjdHMuZ2V0X21vZGVsKHNlbGYubW9kZWxfcGF0aCkKCiAgICAgICAgIyBSZWFkIHRoZSBuYW1lOgogICAgICAgIG1vZGVsX25hbWUgPSBtb2RlbF9hcnRpZmFjdC5zcGVjLmRiX2tleQoKICAgICAgICAjIEV4dHJhY3QgbG9nZ2VkIG1vZGVsIGZpbGVzOgogICAgICAgIG1vZGVsX2RpcmVjdG9yeSA9IG9zLnBhdGguam9pbihvcy5wYXRoLmRpcm5hbWUobW9kZWxfZmlsZSksIG1vZGVsX25hbWUpCiAgICAgICAgd2l0aCB6aXBmaWxlLlppcEZpbGUobW9kZWxfZmlsZSwgInIiKSBhcyB6aXBfZmlsZToKICAgICAgICAgICAgemlwX2ZpbGUuZXh0cmFjdGFsbChtb2RlbF9kaXJlY3RvcnkpCgogICAgICAgICMgTG9hZGluZyB0aGUgc2F2ZWQgcHJldHJhaW5lZCB0b2tlbml6ZXIgYW5kIG1vZGVsOgogICAgICAgIHNlbGYudG9rZW5pemVyID0gc2VsZi5fdG9rZW5pemVyX2NsYXNzLmZyb21fcHJldHJhaW5lZChtb2RlbF9kaXJlY3RvcnkpCiAgICAgICAgc2VsZi5tb2RlbCA9IHNlbGYuX21vZGVsX2NsYXNzLmZyb21fcHJldHJhaW5lZChtb2RlbF9kaXJlY3RvcnkpCgogICAgZGVmIF9sb2FkX2Zyb21faHViKHNlbGYpOgogICAgICAgICMgTG9hZGluZyB0aGUgcHJldHJhaW5lZCB0b2tlbml6ZXIgYW5kIG1vZGVsOgogICAgICAgIHNlbGYudG9rZW5pemVyID0gc2VsZi5fdG9rZW5pemVyX2NsYXNzLmZyb21fcHJldHJhaW5lZCgKICAgICAgICAgICAgc2VsZi50b2tlbml6ZXJfbmFtZSwKICAgICAgICAgICAgbW9kZWxfbWF4X2xlbmd0aD01MTIsCiAgICAgICAgKQogICAgICAgIHNlbGYubW9kZWwgPSBzZWxmLl9tb2RlbF9jbGFzcy5mcm9tX3ByZXRyYWluZWQoc2VsZi5tb2RlbF9uYW1lKQoKICAgIGRlZiBwcmVkaWN0KHNlbGYsIHJlcXVlc3Q6IERpY3Rbc3RyLCBBbnldKSAtPiBkaWN0OgogICAgICAgICMgR2V0IHRoZSBpbnB1dHM6CiAgICAgICAgcHJvbXB0ID0gcmVxdWVzdFsiaW5wdXRzIl1bMF0KCiAgICAgICAgIyBUb2tlbml6ZToKICAgICAgICBpbnB1dF9pZHMgPSBzZWxmLnRva2VuaXplci5lbmNvZGUocHJvbXB0LCByZXR1cm5fdGVuc29ycz0icHQiKQoKICAgICAgICAjIENyZWF0ZSB0aGUgYXR0ZW50aW9uIG1hc2sgYW5kIHBhZCB0b2tlbiBpZDoKICAgICAgICBhdHRlbnRpb25fbWFzayA9IHRvcmNoLm9uZXNfbGlrZShpbnB1dF9pZHMpCiAgICAgICAgcGFkX3Rva2VuX2lkID0gc2VsZi50b2tlbml6ZXIuZW9zX3Rva2VuX2lkCgogICAgICAgICMgSW5mZXIgdGhyb3VnaCB0aGUgbW9kZWw6CiAgICAgICAgb3V0cHV0ID0gc2VsZi5tb2RlbC5nZW5lcmF0ZSgKICAgICAgICAgICAgaW5wdXRfaWRzLAogICAgICAgICAgICBtYXhfbGVuZ3RoPXNlbGYucmVzcG9uc2VfbWF4X2xlbmd0aCwKICAgICAgICAgICAgZG9fc2FtcGxlPUZhbHNlLAogICAgICAgICAgICB0b3Bfaz01MCwKICAgICAgICAgICAgdG9wX3A9MC45LAogICAgICAgICAgICB0ZW1wZXJhdHVyZT0wLjksCiAgICAgICAgICAgIG51bV9yZXR1cm5fc2VxdWVuY2VzPTEsCiAgICAgICAgICAgIGF0dGVudGlvbl9tYXNrPWF0dGVudGlvbl9tYXNrLAogICAgICAgICAgICBwYWRfdG9rZW5faWQ9cGFkX3Rva2VuX2lkLAogICAgICAgICkKCiAgICAgICAgIyBEZXRva2VuaXplOgogICAgICAgIHByZWRpY3Rpb24gPSBzZWxmLnRva2VuaXplci5kZWNvZGUob3V0cHV0WzBdLCBza2lwX3NwZWNpYWxfdG9rZW5zPVRydWUpCgogICAgICAgIHJldHVybiB7InByZWRpY3Rpb24iOiBwcmVkaWN0aW9uLCAicHJvbXB0IjogcHJvbXB0fQoKICAgIGRlZiBleHBsYWluKHNlbGYsIHJlcXVlc3Q6IERpY3QpIC0+IHN0cjoKICAgICAgICByZXR1cm4gZiJMTE0gbW9kZWwgc2VydmVyIG5hbWVkIHtzZWxmLm5hbWV9IgoKCmRlZiBwb3N0cHJvY2VzcyhpbnB1dHM6IGRpY3QpIC0+IGRpY3Q6CiAgICAjIFJlYWQgdGhlIHByZWRpY3Rpb246CiAgICBwcmVkaWN0aW9uID0gaW5wdXRzWyJvdXRwdXRzIl1bInByZWRpY3Rpb24iXQoKICAgICMgTG9vayBmb3IgYSAnQ29udGVudDogJyBtYXJrIHRvIGtub3cgdGhlIG1vZGVsIGZvdW5kIHRoZSBzdWJqZWN0LCBvdGhlcndpc2UsIGl0IGlzIHByb2JhYmx5IGdhcmJhZ2U6CiAgICBjb250ZW50X2luZGV4ID0gcHJlZGljdGlvbi5maW5kKENPTlRFTlRfTUFSSykKICAgIGlmIGNvbnRlbnRfaW5kZXggPT0gLTE6CiAgICAgICAgb3V0cHV0ID0gZiJJJ20gbm90IHN1cmUgYWJvdXQgaXQgYnV0IEknbGwgZG8gbXkgYmVzdDoge3ByZWRpY3Rpb259IgogICAgZWxzZToKICAgICAgICBvdXRwdXQgPSBwcmVkaWN0aW9uW2NvbnRlbnRfaW5kZXggKyBsZW4oQ09OVEVOVF9NQVJLKSA6XQoKICAgIHJldHVybiB7ImlucHV0cyI6IFt7InByZWRpY3Rpb24iOiBvdXRwdXQsICJwcm9tcHQiOiBpbnB1dHNbIm91dHB1dHMiXVsicHJvbXB0Il19XX0KCgpkZWYgY2xlYW5fcG9zdHByb2Nlc3MoaW5wdXRzOiBkaWN0KSAtPiBkaWN0OgogICAgcmV0dXJuIHsiaW5wdXRzIjogW2lucHV0c1sib3V0cHV0cyJdXX0KCgpjbGFzcyBUb3hpY2l0eUNsYXNzaWZpZXJNb2RlbFNlcnZlcihWMk1vZGVsU2VydmVyKToKICAgIGRlZiBfX2luaXRfXyhzZWxmLCBjb250ZXh0LCBuYW1lOiBzdHIsIHRocmVzaG9sZDogZmxvYXQgPSAwLjcsICoqY2xhc3NfYXJncyk6CiAgICAgICAgIyBJbml0aWFsaXplIHRoZSBiYXNlIHNlcnZlcjoKICAgICAgICBzdXBlcihUb3hpY2l0eUNsYXNzaWZpZXJNb2RlbFNlcnZlciwgc2VsZikuX19pbml0X18oCiAgICAgICAgICAgIGNvbnRleHQ9Y29udGV4dCwKICAgICAgICAgICAgbmFtZT1uYW1lLAogICAgICAgICAgICBtb2RlbF9wYXRoPU5vbmUsCiAgICAgICAgICAgICoqY2xhc3NfYXJncywKICAgICAgICApCgogICAgICAgICMgU3RvcmUgdGhlIHRocmVzaG9sZCBvZiB0b3hpY2l0eToKICAgICAgICBzZWxmLnRocmVzaG9sZCA9IHRocmVzaG9sZAoKICAgIGRlZiBsb2FkKHNlbGYpOgogICAgICAgIHNlbGYubW9kZWwgPSBldmFsdWF0ZS5sb2FkKCJ0b3hpY2l0eSIsIG1vZHVsZV90eXBlPSJtZWFzdXJlbWVudCIpCgogICAgZGVmIHByZWRpY3Qoc2VsZiwgaW5wdXRzOiBEaWN0KSAtPiBzdHI6CiAgICAgICAgIyBSZWFkIHRoZSB1c2VyJ3MgaW5wdXQgYW5kIG1vZGVsIG91dHB1dDoKICAgICAgICBwcmVkaWN0aW9uID0gaW5wdXRzWyJpbnB1dHMiXVswXVsicHJlZGljdGlvbiJdCiAgICAgICAgcHJvbXB0ID0gaW5wdXRzWyJpbnB1dHMiXVswXVsicHJvbXB0Il0KCiAgICAgICAgIyBJbmZlciB0aHJvdWdoIHRoZSBldmFsdWF0b3IgbW9kZWw6CiAgICAgICAgcmVzdWx0ID0gc2VsZi5tb2RlbC5jb21wdXRlKHByZWRpY3Rpb25zPVtwcmVkaWN0aW9uLCBwcm9tcHRdKVsidG94aWNpdHkiXQogICAgICAgIGlmIGFueShucC5hcnJheShyZXN1bHQpID4gc2VsZi50aHJlc2hvbGQpOgogICAgICAgICAgICByZXR1cm4gIk1MUnVuIGRvZXMgbm90IGFsbG93IHRveGljaXR5ISIKCiAgICAgICAgcmV0dXJuIHByZWRpY3Rpb24KCiAgICBkZWYgZXhwbGFpbihzZWxmLCByZXF1ZXN0OiBEaWN0KSAtPiBzdHI6CiAgICAgICAgcmV0dXJuIGYiVGV4dCB0b3hpY2l0eSBjbGFzc2lmaWVyIHNlcnZlciBuYW1lZCB7c2VsZi5uYW1lfSIKCmZyb20gbWxydW4ucnVudGltZXMgaW1wb3J0IG51Y2xpb19pbml0X2hvb2sKZGVmIGluaXRfY29udGV4dChjb250ZXh0KToKICAgIG51Y2xpb19pbml0X2hvb2soY29udGV4dCwgZ2xvYmFscygpLCAnc2VydmluZ192MicpCgpkZWYgaGFuZGxlcihjb250ZXh0LCBldmVudCk6CiAgICByZXR1cm4gY29udGV4dC5tbHJ1bl9oYW5kbGVyKGNvbnRleHQsIGV2ZW50KQo=
          source: ./
          commands: []
          code_origin: git://github.com/yonishelach/learn-docs.git#refs/heads/main
          origin_filename: src/serving.py
        description: ''
        default_handler: ''
        disable_auto_mount: false
        env: []
        resources:
          requests:
            memory: 1Mi
            cpu: 25m
          limits:
            nvidia.com/gpu: 4
            memory: 244Gi
            cpu: 32
        image_pull_secret: docker-registry-admin-creds
        priority_class_name: igz-workload-medium
        preemption_mode: prevent
        min_replicas: 1
        max_replicas: 4
        source: ''
        function_kind: serving_v2
        function_handler: serving:handler
        base_image_pull: false
        graph:
          steps:
            preprocess:
              kind: task
              handler: clean_preprocess
              after: []
            gpt2:
              kind: task
              class_name: LLMModelServer
              class_args:
                model_name: gpt2-medium
                model_class: GPT2LMHeadModel
                tokenizer_name: gpt2-medium
                tokenizer_class: GPT2Tokenizer
                use_deepspeed: true
                n_gpus: 4
              after:
              - preprocess
            postprocess:
              kind: task
              handler: clean_postprocess
              after:
              - gpt2
            toxicity-classifier:
              kind: task
              class_name: ToxicityClassifierModelServer
              class_args:
                threshold: 0.7
              after:
              - postprocess
              responder: true
          engine: async
        secret_sources: []
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: app.iguazio.com/lifecycle
                  operator: NotIn
                  values:
                  - preemptible
                - key: eks.amazonaws.com/capacityType
                  operator: NotIn
                  values:
                  - SPOT
                - key: node-lifecycle
                  operator: NotIn
                  values:
                  - spot
        tolerations: null
        security_context: {}
      verbose: false
  workflows:
  - path: src/training_workflow.py
    name: training_workflow
  artifacts: []
  conda: ''
  source: git://github.com/yonishelach/learn-docs.git#main
  origin_url: git://github.com/yonishelach/learn-docs.git#refs/heads/main
  load_source_on_run: true
  desired_state: online
  owner: admin
  default_image: yonishelach/mlrun-hf
status:
  state: online
